### ISSUE TITLE
Terminators in X-bar tree

### ISSUE THREAD

**Issue by lynn** [toaq/zugai#10]
🥲

**Comment by solpahi** [comment]
For any phrase YP which is associated with a terminator, there is a projection Y<sub>F</sub>P such that Y<sub>F</sub> is the terminator associated with Y:

![image](https://user-images.githubusercontent.com/7430686/184324491-79fff37a-655c-42fc-a0d0-7f51e2d7fdf6.png)

(F = final particle)

**CP**:
![image](https://user-images.githubusercontent.com/7430686/184325267-c15b11b3-cc5b-42a3-b337-b0c9a5139eec.png)

**PO**:
![image](https://user-images.githubusercontent.com/7430686/184326740-7043f8c5-b3e1-4e04-83fa-2d10f6832f1e.png)

and so on.

(The Y<sub>F</sub> naming convention is arbitrary.)

**Comment by lynn** [comment]
We have this style of terminators now.
