### ISSUE TITLE
Simplify (TAMN V*)+ serials

### ISSUE THREAD

**Issue by solpahi** [toaq/zugai#21]
I think we can simplify (TAMN V*)+ serials by putting F above T.

Example serial: **naı chı jıa faq**

![image](https://user-images.githubusercontent.com/7430686/184497882-c0d6bece-bbdc-48ac-9338-38ab7b253a7c.png)

(Low) adverbials have to attach to the highest VP/vP to make sure they still end up below T (specifically the T right below FP, heading the entire serial, if there is one. This does not apply to TPs that are buried in the serial).

![image](https://user-images.githubusercontent.com/7430686/184498154-b0b584f3-976f-4c00-85ea-fd1a0a9839d7.png)

With F above T, the F head can do the job of carrying :t9:, aka the proposed new verb tone that isn't the serial tone. This way, F makes an actual contribution beyond serving as a movement target. However, the simplification does not depend on the adoption of the proposal (F can just remain null).

With this, every serial would look the same, whether it contains TAMN components or not:

![image](https://user-images.githubusercontent.com/7430686/184498506-4543d6b9-7b92-4101-8272-0530e736306b.png)

**Comment by lynn** [comment]
I implemented this simplification :+1:
